[package]
name = "dasp_sample"
description = "An abstraction for audio PCM DSP samples, along with useful conversions and operations."
version = "0.11.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
readme = "../README.md"
keywords = ["dsp", "bit-depth", "sample", "pcm", "audio"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rustaudio/sample.git"
homepage = "https://github.com/rustaudio/sample"
edition = "2018"

[features]
default = ["std"]
std = []

[package.metadata.docs.rs]
all-features = true
